['A830_TALON_U_61.06.00I']
specs = { soc = 'RAINBOW', toolchain = 'GCC_MCORE' }
flags.general = '-DFTR_A830 -DFTR_DEBUG'
flags.bin_ldr = '-DFTR_LOGGER -DFTR_LOGGER_JAL -DFTR_ALLOC_SUAPI -DFTR_NO_VSNPRINTF'
flags.elf_ldr = '-DFTR_LOGGER -DFTR_LOGGER_JAL -DFTR_ALLOC_SUAPI'
addrs = { inject = 0x10900000, loader = 0x079DE2F4, register = 0x106CF134, task_a = 0x1053B4E4, task_b = 0x1053BB44 }

['C330_TA02_G_06.03.25R_elf']
specs = { soc = 'NEPTUNE_LT_LCA', toolchain = 'GCC_ARM' }
flags.general = '-DFTR_C330 -DFTR_DEBUG'
flags.bin_ldr = '-DFTR_LOGGER -DFTR_LOGGER_NULL -DFTR_ALLOC_SUAPI -DFTR_NO_VSNPRINTF'
flags.elf_ldr = '-DFTR_LOGGER -DFTR_LOGGER_NULL -DFTR_ALLOC_SUAPI'
addrs = { inject = 0x00570000, loader = 0x1106B030, register = 0x004307FC, task_a = 0x00078F78, task_b = 0x0007896C }

['E1_R373_G_0E.30.44R_elf']
specs = { soc = 'NEPTUNE_LTE', toolchain = 'GCC_ARM' }
flags.general = '-DFTR_E1 -DFTR_DEBUG'
flags.bin_ldr = '-DFTR_LOGGER -DFTR_LOGGER_JAL -DFTR_ALLOC_SUAPI'
flags.elf_ldr = '-DFTR_LOGGER -DFTR_LOGGER_JAL -DFTR_ALLOC_SUAPI'
addrs = { inject = 0x108A8F1C, loader = 0x1279A560, register = 0x103F977C, task_a = 0x10A5D494, task_b = 0x10A5E5EC }
