from pathlib import Path

from .aleph_format_def import AlephFormatDef
from .aleph_logger import AlephLogger
from .aleph_checker import AlephChecker, CheckerMode
from .aleph_model_def import AlephModelDef, SymbolDef
from .aleph_filesystem import AlephFileSystem
from .aleph_stringer import AlephStringer
from .aleph_hexer import AlephHexer
from .aleph_patcher import AlephPatcher
from .aleph_exception import AlephParserException

class AlephFormatMap(AlephFormatDef):
	def __init__(
		self,
		logger: AlephLogger,
		checker: AlephChecker,
		mdef: AlephModelDef,
		filesystem: AlephFileSystem,
		stringer: AlephStringer,
		hexer: AlephHexer,
		patcher: AlephPatcher
	) -> None:
		super().__init__(logger, checker, mdef, filesystem, stringer, hexer, patcher)

	def parse_validate_line(self, line: str) -> SymbolDef:
		self.chk.is_ok_str(line, CheckerMode.EXCEPTION)

		parts = line.split()

		if len(parts) != 3:
			raise AlephParserException(f'Too many (more than 3) parts inside line: {line}')

		def_addr_str, def_type, def_name = parts
		def_addr = self.hex.u32i('0x' + def_addr_str)

		# Symbols cannot be validated for .map files generated by `nm` since it uses other type format, see:
		# https://sourceware.org/binutils/docs/binutils/nm.html
		return SymbolDef(def_addr, def_type, def_name)

	def read_map(self, p_i: Path) -> list[SymbolDef]:
		self.chk.check_ext(p_i, ['.map'], CheckerMode.EXCEPTION)
		lines_c = self.fs.read_text_lines(p_i)
		self.chk.is_ok_list(lines_c, CheckerMode.EXCEPTION)

		body = self.parse_validate_body(lines_c)
		self.chk.is_ok_list(body, CheckerMode.EXCEPTION)
		return body

	def find_map_sym(self, p_i: Path, by_addr_or_name: int | str) -> SymbolDef:
		map_syms = self.read_map(p_i)

		if isinstance(by_addr_or_name, str):
			self.chk.is_ok_str(by_addr_or_name, CheckerMode.EXCEPTION)

		find_by_name = (isinstance(by_addr_or_name, str) and not by_addr_or_name[0].isdigit())
		by_addr = by_addr_or_name
		if isinstance(by_addr_or_name, str) and not find_by_name:
			by_addr = self.hex.u32i(by_addr_or_name)

		check_duplicates = []
		for map_sym in map_syms:
			if find_by_name:
				if map_sym.name == by_addr_or_name:
					check_duplicates.append(map_sym)
			else:
				if map_sym.addr == by_addr:
					check_duplicates.append(map_sym)

		self.chk.is_ok_list(check_duplicates, CheckerMode.EXCEPTION)

		if len(check_duplicates) > 1:
			self.log.W(f'Duplicate symbols found, will return first: {by_addr_or_name}')
			for sym in check_duplicates:
				self.log.W(f' {self.mdef.gen_def_line(sym)}')

		return check_duplicates[0]
